/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuthorizedUser {
  authorizedBy: string;
  chatId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  userId: string;
}

export interface BannedUser {
  createdAt: Generated<Timestamp>;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface BroadcastChat {
  createdAt: Generated<Timestamp>;
  id: string;
  name: string | null;
  updatedAt: Generated<Timestamp>;
  username: string | null;
}

export interface ChatGameTopic {
  chatId: string;
  createdAt: Generated<Timestamp>;
  iconCustomEmojiId: string | null;
  name: string | null;
  shouldRecreateOnExpire: Generated<boolean>;
  topicId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Game {
  chatId: string;
  countryCode: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  startedBy: string | null;
  topicId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Guess {
  createdAt: Generated<Timestamp>;
  distanceKm: number;
  gameId: number;
  guessCode: string;
  id: Generated<number>;
}

export interface Leaderboard {
  chatId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  score: number;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  id: string;
  name: string;
  updatedAt: Generated<Timestamp>;
  username: string | null;
}

export interface DB {
  authorizedUsers: AuthorizedUser;
  bannedUsers: BannedUser;
  broadcastChats: BroadcastChat;
  chatGameTopics: ChatGameTopic;
  games: Game;
  guesses: Guess;
  leaderboard: Leaderboard;
  users: User;
}
